#===----------------------------------------------------------------------===#
# Preset for the WebAssembly toolchain and SDK
#===----------------------------------------------------------------------===#

[preset: webassembly]
skip-build-benchmarks
llvm-targets-to-build=X86;AArch64;WebAssembly
swift-darwin-supported-archs=%(HOST_ARCHITECTURE)s
compiler-vendor=swiftwasm
enable-experimental-concurrency=1
enable-experimental-differentiable-programming=1
enable-experimental-distributed=1

[preset: webassembly-install]

release
assertions
install-swift
install-destdir=%(INSTALL_DESTDIR)s
swift-install-components=autolink-driver;compiler;clang-resource-dir-symlink;stdlib;sdk-overlay;editor-integration;tools;testsuite-tools;toolchain-tools;license;sourcekit-inproc;swift-remote-mirror;swift-remote-mirror-headers
llvm-install-components=llvm-cov;llvm-profdata;IndexStore;clang;clang-resource-headers;compiler-rt;clangd;dsymutil;lld;llvm-ar;llvm-ranlib
install-prefix=/usr


[preset: webassembly-host]

mixin-preset=webassembly
sccache
extra-cmake-options=
    -DSWIFT_BUILD_SOURCEKIT=FALSE
    -DSWIFT_ENABLE_SOURCEKIT_TESTS=FALSE
    -DSWIFT_BUILD_SYNTAXPARSERLIB=FALSE

[preset: webassembly-host-install]
mixin-preset=
    webassembly-host
    webassembly-install

llbuild
swiftpm
indexstore-db
sourcekit-lsp
build-lld

install-llvm
install-swift
install-llbuild
install-swiftpm
install-sourcekit-lsp
install-swiftsyntax

[preset: webassembly-linux-host-install]

mixin-preset=webassembly-host-install

libdispatch
libicu
foundation
xctest

install-libicu
install-foundation
install-libdispatch
install-xctest

skip-test-libicu
skip-test-foundation
skip-test-libdispatch
skip-test-xctest

[preset: stdlib_base_standalone,host=wasi-wasm32]
skip-build-cmark
skip-early-swift-driver
skip-early-swiftsyntax

build-swift-tools=0
build-llvm=0
host-target=wasi-wasm32
stdlib-deployment-targets=wasi-wasm32

swift-stdlib-single-threaded-concurrency=1
swift-enable-backtracing=0
swift-stdlib-has-dladdr=0
build-swift-remote-mirror=0
build-swift-static-stdlib=1
build-swift-dynamic-stdlib=0

[preset: buildbot,stdlib_RA_standalone,host=wasi-wasm32]
mixin-preset=stdlib_base_standalone,host=wasi-wasm32

release
sccache
verbose

native-swift-tools-path=%(NATIVE_SWIFT_TOOLS_PATH)s
native-clang-tools-path=%(NATIVE_LLVM_TOOLS_PATH)s
native-llvm-tools-path=%(NATIVE_LLVM_TOOLS_PATH)s

extra-cmake-options=
  -DSWIFT_WASI_SYSROOT_PATH="%(WASI_SYSROOT_PATH)s"
  -DSWIFT_WASI_wasm32_ICU_UC_INCLUDE="%(ICU_PATH)s/include"
  -DSWIFT_WASI_wasm32_ICU_UC="%(ICU_PATH)s/lib/libicuuc.a"
  -DSWIFT_WASI_wasm32_ICU_I18N_INCLUDE="%(ICU_PATH)s/include"
  -DSWIFT_WASI_wasm32_ICU_I18N="%(ICU_PATH)s/lib/libicui18n.a"
  -DSWIFT_WASI_wasm32_ICU_DATA="%(ICU_PATH)s/lib/libicudata.a"
  -DCMAKE_RANLIB=%(NATIVE_LLVM_TOOLS_PATH)s/llvm-ranlib
  -DCMAKE_AR=%(NATIVE_LLVM_TOOLS_PATH)s/llvm-ar
  -DSWIFTWASM_DISABLE_REFLECTION_TEST=YES
  -DSWIFT_DRIVER_TEST_OPTIONS=" -Xclang-linker -resource-dir -Xclang-linker %(COMPILER_RT_BUILD_DIR)s"

[preset: mixin_buildbot,stdlib_standalone,host=wasi-wasm32,install]
swift-install-components=stdlib;sdk-overlay;
install-swift
install-destdir=%(INSTALL_DESTDIR)s
install-prefix=/usr

[preset: mixin_buildbot,stdlib,host=wasi-wasm32,test]
test-paths=test/stdlib;test/Concurrency/Runtime

[preset: buildbot,stdlib_RA_standalone,host=wasi-wasm32,install]
mixin-preset=
  buildbot,stdlib_RA_standalone,host=wasi-wasm32
  mixin_buildbot,stdlib_standalone,host=wasi-wasm32,install
  mixin_buildbot,stdlib,host=wasi-wasm32,test
