name: Distribute toolchain
on:
  workflow_call:
    inputs:
      scheme:
        required: true
        type: string
      run-id:
        required: true
        type: string
      override-name:
        type: string

jobs:
  distribution:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: swiftwasm/swiftwasm-build
          path: swiftwasm-build
      - name: git config for pushing tags
        run: git config --global url."https://x-access-token:$GITHUB_TOKEN@github.com/swiftwasm/swift.git".insteadOf "git@github.com:swiftwasm/swift.git"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup environment variables
        run: |
          if [[ -n "${{ github.event.inputs.override-name }}" ]]; then
            echo "GH_DISTRIBUTE_TOOLCHAIN_OVERRIDE_NAME=${{ github.event.inputs.override-name }}" >> $GITHUB_ENV
          fi
      - uses: nick-fields/retry@v4
        with:
          timeout_minutes: 180
          max_attempts: 3
          retry_on: error
          command: |
            cd swiftwasm-build
            ./tools/gh-distribute-toolchain --scheme ${{ inputs.scheme }} --verbose --skip-history ${{ inputs.run-id }}
          on_retry_command: |
            rm -rf "build/Distribution/artifacts"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
