name: Manual distribution
on:
  workflow_dispatch:
    inputs:
      scheme:
        required: true
        type: string
        description:  "Scheme to distribute (e.g. main, release-5.9, ...)"
      run-id:
        required: true
        type: string
        description: 'GitHub Actions run id in swiftwasm/swiftwasm-build'
      override-name:
        type: string
        description: 'Toolchain name'
jobs:
  manual-distribution:
    uses: ./.github/workflows/distribute-toolchain.yml
    secrets: inherit
    with:
      scheme: ${{ inputs.scheme }}
      run-id: ${{ inputs.run-id }}
      override-name: ${{ inputs.override-name }}
